spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.output:
  destination: counts
spring.cloud.stream.bindings.input:
  destination: words
spring.cloud.stream.kafka.streams.bindings.input:
  consumer:
    application-id: input1-stream-listener
spring.cloud.stream.bindings.foobar:
  destination: comeon
spring.cloud.stream.kafka.streams.bindings.foobar:
  consumer:
    application-id: foobar-stream-listener



